// <auto-generated />
using System;
using EnergyLinkGlobalSolution.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EnergyLinkGlobalSolution.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20241122062043_ExecuteProject")]
    partial class ExecuteProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnergyLinkGlobalSolution.Models.Entidade", b =>
                {
                    b.Property<int>("IdEntidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ENTIDADE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEntidade"));

                    b.HasKey("IdEntidade");

                    b.ToTable("ENTIDADE_BASE");
                });

            modelBuilder.Entity("EnergyLinkGlobalSolution.Models.Monitoramento", b =>
                {
                    b.Property<int>("IdMonitoramento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MONITORAMENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMonitoramento"));

                    b.Property<DateTime>("DataMonitoramento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_MONITORAMENTO");

                    b.Property<int>("Energia")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ENERGIA");

                    b.Property<int>("IdEntidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ENTIDADE");

                    b.Property<string>("TipoMonitoramento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPO_MONITORAMENTO");

                    b.HasKey("IdMonitoramento");

                    b.HasIndex("IdEntidade");

                    b.ToTable("MONITORAMENTO_ENERGIA");
                });

            modelBuilder.Entity("EnergyLinkGlobalSolution.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CPF_USUARIO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL_USUARIO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME_USUARIO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SENHA_USUARIO");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SOBRENOME_USUARIO");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TELEFONE_USUARIO");

                    b.HasKey("IdUsuario");

                    b.ToTable("USUARIO_ENERGYLINK");
                });

            modelBuilder.Entity("EnergyLinkGlobalSolution.Models.Monitoramento", b =>
                {
                    b.HasOne("EnergyLinkGlobalSolution.Models.Entidade", "Entidade")
                        .WithMany()
                        .HasForeignKey("IdEntidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entidade");
                });
#pragma warning restore 612, 618
        }
    }
}
